# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window2.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 611)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Input_Group = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_Group.sizePolicy().hasHeightForWidth())
        self.Input_Group.setSizePolicy(sizePolicy)
        self.Input_Group.setMinimumSize(QtCore.QSize(0, 100))
        self.Input_Group.setMaximumSize(QtCore.QSize(16777215, 260))
        self.Input_Group.setObjectName("Input_Group")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Input_Group)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.InQ_Lab = QtWidgets.QLabel(self.Input_Group)
        self.InQ_Lab.setObjectName("InQ_Lab")
        self.horizontalLayout.addWidget(self.InQ_Lab)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.InQ_Text = QtWidgets.QTextBrowser(self.Input_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InQ_Text.sizePolicy().hasHeightForWidth())
        self.InQ_Text.setSizePolicy(sizePolicy)
        self.InQ_Text.setMinimumSize(QtCore.QSize(395, 73))
        self.InQ_Text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.InQ_Text.setObjectName("InQ_Text")
        self.verticalLayout_2.addWidget(self.InQ_Text)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.InSql_Lab = QtWidgets.QLabel(self.Input_Group)
        self.InSql_Lab.setObjectName("InSql_Lab")
        self.horizontalLayout_2.addWidget(self.InSql_Lab)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.InSql_Text = QtWidgets.QTextBrowser(self.Input_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InSql_Text.sizePolicy().hasHeightForWidth())
        self.InSql_Text.setSizePolicy(sizePolicy)
        self.InSql_Text.setMinimumSize(QtCore.QSize(395, 80))
        self.InSql_Text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.InSql_Text.setObjectName("InSql_Text")
        self.verticalLayout_2.addWidget(self.InSql_Text)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.Ok_But = QtWidgets.QPushButton(self.Input_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ok_But.sizePolicy().hasHeightForWidth())
        self.Ok_But.setSizePolicy(sizePolicy)
        self.Ok_But.setMinimumSize(QtCore.QSize(75, 40))
        self.Ok_But.setObjectName("Ok_But")
        self.verticalLayout.addWidget(self.Ok_But)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem7)
        self.Reset_But = QtWidgets.QPushButton(self.Input_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reset_But.sizePolicy().hasHeightForWidth())
        self.Reset_But.setSizePolicy(sizePolicy)
        self.Reset_But.setMinimumSize(QtCore.QSize(0, 40))
        self.Reset_But.setObjectName("Reset_But")
        self.verticalLayout.addWidget(self.Reset_But)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.Input_Group, 0, 0, 1, 1)
        self.Derivative_Group = QtWidgets.QGroupBox(self.centralwidget)
        self.Derivative_Group.setObjectName("Derivative_Group")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Derivative_Group)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SonQ_Lab = QtWidgets.QLabel(self.Derivative_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SonQ_Lab.sizePolicy().hasHeightForWidth())
        self.SonQ_Lab.setSizePolicy(sizePolicy)
        self.SonQ_Lab.setMinimumSize(QtCore.QSize(0, 0))
        self.SonQ_Lab.setMaximumSize(QtCore.QSize(16777215, 35))
        self.SonQ_Lab.setObjectName("SonQ_Lab")
        self.horizontalLayout_5.addWidget(self.SonQ_Lab)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.SonQ_Tab = QtWidgets.QTableView(self.Derivative_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SonQ_Tab.sizePolicy().hasHeightForWidth())
        self.SonQ_Tab.setSizePolicy(sizePolicy)
        self.SonQ_Tab.setMinimumSize(QtCore.QSize(0, 220))
        self.SonQ_Tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SonQ_Tab.setObjectName("SonQ_Tab")
        self.verticalLayout_5.addWidget(self.SonQ_Tab)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SonSql_Lab = QtWidgets.QLabel(self.Derivative_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SonSql_Lab.sizePolicy().hasHeightForWidth())
        self.SonSql_Lab.setSizePolicy(sizePolicy)
        self.SonSql_Lab.setMinimumSize(QtCore.QSize(0, 35))
        self.SonSql_Lab.setMaximumSize(QtCore.QSize(16777215, 35))
        self.SonSql_Lab.setObjectName("SonSql_Lab")
        self.horizontalLayout_4.addWidget(self.SonSql_Lab)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.SonSQL_Tab = QtWidgets.QTableView(self.Derivative_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SonSQL_Tab.sizePolicy().hasHeightForWidth())
        self.SonSQL_Tab.setSizePolicy(sizePolicy)
        self.SonSQL_Tab.setMinimumSize(QtCore.QSize(0, 220))
        self.SonSQL_Tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SonSQL_Tab.setObjectName("SonSQL_Tab")
        self.verticalLayout_4.addWidget(self.SonSQL_Tab)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.Derivative_Group, 0, 1, 2, 1)
        self.SearchRes_Group = QtWidgets.QGroupBox(self.centralwidget)
        self.SearchRes_Group.setObjectName("SearchRes_Group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.SearchRes_Group)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SearchRes_Tab = QtWidgets.QTableView(self.SearchRes_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchRes_Tab.sizePolicy().hasHeightForWidth())
        self.SearchRes_Tab.setSizePolicy(sizePolicy)
        self.SearchRes_Tab.setMinimumSize(QtCore.QSize(460, 216))
        self.SearchRes_Tab.setObjectName("SearchRes_Tab")
        self.verticalLayout_3.addWidget(self.SearchRes_Tab)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.SearchRes_Group, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 23))
        self.menubar.setObjectName("menubar")
        self.Chose_Help = QtWidgets.QMenu(self.menubar)
        self.Chose_Help.setObjectName("Chose_Help")
        self.Chose_About = QtWidgets.QMenu(self.menubar)
        self.Chose_About.setObjectName("Chose_About")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.Chose_Help.menuAction())
        self.menubar.addAction(self.Chose_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Input_Group.setTitle(_translate("MainWindow", "Input the Request"))
        self.InQ_Lab.setText(_translate("MainWindow", "请输入要查询的自然语言："))
        self.InSql_Lab.setText(_translate("MainWindow", "请输入要查询的SQL语句："))
        self.Ok_But.setText(_translate("MainWindow", "查询"))
        self.Reset_But.setText(_translate("MainWindow", "重置"))
        self.Derivative_Group.setTitle(_translate("MainWindow", "Output the Derivative problems"))
        self.SonQ_Lab.setText(_translate("MainWindow", "衍生的查询自然语言"))
        self.SonSql_Lab.setText(_translate("MainWindow", "衍生的查询SQL语言"))
        self.SearchRes_Group.setTitle(_translate("MainWindow", "Search Result 原询问查询结果"))
        self.Chose_Help.setTitle(_translate("MainWindow", "帮助"))
        self.Chose_About.setTitle(_translate("MainWindow", "关于"))
