# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.InputQ_text = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputQ_text.sizePolicy().hasHeightForWidth())
        self.InputQ_text.setSizePolicy(sizePolicy)
        self.InputQ_text.setMaximumSize(QtCore.QSize(16777215, 110))
        self.InputQ_text.setObjectName("InputQ_text")
        self.verticalLayout_2.addWidget(self.InputQ_text)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.InputSql_text = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputSql_text.sizePolicy().hasHeightForWidth())
        self.InputSql_text.setSizePolicy(sizePolicy)
        self.InputSql_text.setMaximumSize(QtCore.QSize(16777215, 110))
        self.InputSql_text.setObjectName("InputSql_text")
        self.verticalLayout_2.addWidget(self.InputSql_text)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Cancle_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Cancle_Button.setObjectName("Cancle_Button")
        self.gridLayout.addWidget(self.Cancle_Button, 2, 1, 1, 1)
        self.Ask_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Ask_Button.setObjectName("Ask_Button")
        self.gridLayout.addWidget(self.Ask_Button, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem5)
        self.InputQ_Lab = QtWidgets.QLabel(self.centralwidget)
        self.InputQ_Lab.setObjectName("InputQ_Lab")
        self.verticalLayout.addWidget(self.InputQ_Lab)
        spacerItem6 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem6)
        self.InputSql_Lab = QtWidgets.QLabel(self.centralwidget)
        self.InputSql_Lab.setObjectName("InputSql_Lab")
        self.verticalLayout.addWidget(self.InputSql_Lab)
        spacerItem7 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.ResFather_Lab = QtWidgets.QLabel(self.centralwidget)
        self.ResFather_Lab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ResFather_Lab.setAlignment(QtCore.Qt.AlignCenter)
        self.ResFather_Lab.setObjectName("ResFather_Lab")
        self.horizontalLayout_4.addWidget(self.ResFather_Lab)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem10 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem10)
        self.ResFather_Tab = QtWidgets.QTableView(self.centralwidget)
        self.ResFather_Tab.setObjectName("ResFather_Tab")
        self.verticalLayout_5.addWidget(self.ResFather_Tab)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 6, 0, 1, 5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SonQ_Lab = QtWidgets.QLabel(self.centralwidget)
        self.SonQ_Lab.setObjectName("SonQ_Lab")
        self.horizontalLayout.addWidget(self.SonQ_Lab)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.SonQ_List = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SonQ_List.sizePolicy().hasHeightForWidth())
        self.SonQ_List.setSizePolicy(sizePolicy)
        self.SonQ_List.setMaximumSize(QtCore.QSize(16777215, 150))
        self.SonQ_List.setObjectName("SonQ_List")
        self.verticalLayout_4.addWidget(self.SonQ_List)
        spacerItem12 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem12)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.SonSql_Lab = QtWidgets.QLabel(self.centralwidget)
        self.SonSql_Lab.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SonSql_Lab.setObjectName("SonSql_Lab")
        self.horizontalLayout_2.addWidget(self.SonSql_Lab)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.SonSql_List = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SonSql_List.sizePolicy().hasHeightForWidth())
        self.SonSql_List.setSizePolicy(sizePolicy)
        self.SonSql_List.setMaximumSize(QtCore.QSize(16777215, 150))
        self.SonSql_List.setObjectName("SonSql_List")
        self.verticalLayout_3.addWidget(self.SonSql_List)
        spacerItem14 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem14)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 5)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 2, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem16, 5, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem17, 4, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem18, 1, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(5, 1, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem20, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.Menubar = QtWidgets.QMenuBar(MainWindow)
        self.Menubar.setGeometry(QtCore.QRect(0, 0, 600, 23))
        self.Menubar.setObjectName("Menubar")
        self.Help = QtWidgets.QMenu(self.Menubar)
        self.Help.setObjectName("Help")
        MainWindow.setMenuBar(self.Menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Menubar.addAction(self.Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "高考数据查询-YYOL组"))
        self.Cancle_Button.setText(_translate("MainWindow", "查询"))
        self.Ask_Button.setText(_translate("MainWindow", "查询"))
        self.InputQ_Lab.setText(_translate("MainWindow", "请输入要查询的自然语言："))
        self.InputSql_Lab.setText(_translate("MainWindow", "请输入要查询的SQL语句："))
        self.ResFather_Lab.setText(_translate("MainWindow", "原始语句查询结果"))
        self.SonQ_Lab.setText(_translate("MainWindow", "衍生的查询自然语言："))
        self.SonSql_Lab.setText(_translate("MainWindow", "：衍生的SQL查询语句"))
        self.Help.setTitle(_translate("MainWindow", "帮助"))
